// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdB52y7bj5h97zZJVLkXBiSs683dqZoLM',
    appId: '1:615916097653:web:3f07ac065bcd6fb418a83c',
    messagingSenderId: '615916097653',
    projectId: 'proj1-2fb5e',
    authDomain: 'proj1-2fb5e.firebaseapp.com',
    storageBucket: 'proj1-2fb5e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbsyBIhBMeJWv8YK7-1cZC_2XR2yduSo',
    appId: '1:615916097653:android:7adc77b769e4f3fb18a83c',
    messagingSenderId: '615916097653',
    projectId: 'proj1-2fb5e',
    storageBucket: 'proj1-2fb5e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9-8PsY_kps8MIH8RgQZdld-_xFFmKYpQ',
    appId: '1:615916097653:ios:530c0e6b0e65394f18a83c',
    messagingSenderId: '615916097653',
    projectId: 'proj1-2fb5e',
    storageBucket: 'proj1-2fb5e.appspot.com',
    iosBundleId: 'com.example.mentorTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9-8PsY_kps8MIH8RgQZdld-_xFFmKYpQ',
    appId: '1:615916097653:ios:530c0e6b0e65394f18a83c',
    messagingSenderId: '615916097653',
    projectId: 'proj1-2fb5e',
    storageBucket: 'proj1-2fb5e.appspot.com',
    iosBundleId: 'com.example.mentorTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdB52y7bj5h97zZJVLkXBiSs683dqZoLM',
    appId: '1:615916097653:web:e5775d6c15ccd72418a83c',
    messagingSenderId: '615916097653',
    projectId: 'proj1-2fb5e',
    authDomain: 'proj1-2fb5e.firebaseapp.com',
    storageBucket: 'proj1-2fb5e.appspot.com',
  );
}
